### ISSUE TITLE
Unable to launch with beta versions of JDK

### ISSUE THREAD

**Issue by ck-aditya** [ccavanaugh/jgnash#71]
## Actual Behavior
Unable to launch the application when launched with the beta version of JDK.

## Exception:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.NumberFormatException: For input string: "202-ea"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at jgnash.resource.util.OS.getJavaRelease(OS.java:84)
	at jGnashFx.main(jGnashFx.java:83)
	... 11 more
Exception running application jGnashFx

## Steps to Reproduce the Problem
  1. Use the beta version of JDK and try to run the application.

## Specifications
  - jGnash Version: "2.36.1"
  - Operating System: "macOS mojave"
  - Java Version: "1.8.0_202-ea"

**Comment by ccavanaugh** [comment]
Fixed for the next release.  Thanks for reporting it!
