### ISSUE TITLE
NPE when closing jGnash v3.0.1

### ISSUE THREAD

**Issue by kumarpranay** [ccavanaugh/jgnash#78]
## Specifications

  - jGnash Version: 3.0.1
  - Operating System: MacOS 10.14.4
  - Java Version: 
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

## Description
Opened the software. Made new entries and reconciled one account and then hit the "Close" button. Got an NPE on the console. Now the file would not close no matter how many times I hit the close button. Had to abort. Work was not lost luckily.

## Console Output
[2019-04-03 08:19:54] [SEVERE ] {jgnash.uifx.StaticUIMethods$ExceptionHandler uncaughtException} null
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at jgnash.uifx.views.recurring.RecurringViewController.showReminderDialog(RecurringViewController.java:228)
	at jgnash.uifx.views.recurring.RecurringViewController$1.lambda$run$0(RecurringViewController.java:204)
	at jgnash.uifx.util.JavaFXUtils.lambda$_runLater$0(JavaFXUtils.java:114)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by lukebakken** [comment]
Version `3.0.3` is available. I suggest reproducing this problem with the latest version.

**Comment by ccavanaugh** [comment]
Thanks Pranay, fixed for the next release.
