### ISSUE TITLE
Cannot start on Mac OS X - silicon m1 arm

### ISSUE THREAD

**Issue by Strat1987** [ccavanaugh/jgnash#99]
## Expected Behavior
Startup without exceptions

## Actual Behavior

Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/bertroex/.openjfx/cache/14-ea/libprism_es2.dylib: dlopen(/Users/bertroex/.openjfx/cache/14-ea/libprism_es2.dylib, 0x0001): tried: '/Users/bertroex/.openjfx/cache/14-ea/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libprism_es2.dylib' (no such file)
java.lang.UnsatisfiedLinkError: /Users/bertroex/.openjfx/cache/14-ea/libprism_es2.dylib: dlopen(/Users/bertroex/.openjfx/cache/14-ea/libprism_es2.dylib, 0x0001): tried: '/Users/bertroex/.openjfx/cache/14-ea/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libprism_es2.dylib' (no such file)

## Steps to Reproduce the Problem

  1. extract on mac os x with m1 chip
  2. open

## Specifications

  - jGnash Version: 3.5.1
  - Operating System: macOS 12.0.1
  - Java Version 11.0.14

**Comment by Strat1987** [comment]
using jdk Using java version 17.0.2.fx-zulu opens the app but still gives an error trying to open the xml file.

[2022-02-17 11:32:38] [INFO   ] {jgnash.plugin.PluginFactory getDefaultPluginDirectory} Plugin path: /_path_/jGnash/jGnash-3.5.1/plugins/
[2022-02-17 11:32:38] [INFO   ] {jgnash.plugin.PluginFactory getUserPluginDirectory} Plugin path: /Users/_user_/.jgnash/plugins/
[2022-02-17 11:32:38] [INFO   ] {jgnash.plugin.PluginFactory startPlugins} Starting plugin: MT940 Import
[2022-02-17 11:32:39] [SEVERE ] {jgnash.util.LogUtil logSevere} Operation not supported
java.io.IOException: Operation not supported
	at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:96)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1328)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at jgnash.util.FileUtils.isFileLocked(FileUtils.java:134)
	at jgnash.uifx.tasks.BootEngineTask.call(BootEngineTask.java:93)
	at jgnash.uifx.tasks.BootEngineTask.call(BootEngineTask.java:20)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

[2022-02-17 11:32:42] [INFO   ] {jgnash.plugin.PluginFactory stopPlugins} Stopping plugin: MT940 Import

**Comment by Strat1987** [comment]
I'm loading the xml file from Google Drive and since the latest release it seems to be handled as an external Volume on OS X.

This can be resolved by moving it over to a local folder (which I've then added to be synced using Google Drive)
